### ISSUE TITLE
Implementar función de acceso a base de datos obtener_lista_comprados

### ISSUE THREAD

**Issue by DiegoBielsa** [UNIZAR-30226-2021-13/UniTrivia_backend#20]
Esta función devolverá un array con los identificadores de todos los artículos que el usuario en cuestión tiene en su propiedad

**Comment by danielbenedi6** [comment]
Le sirve de algo a front-end el identificador interno de la bd de los objetos comprados? No le sería más útil el nombre y la imagen?

**Comment by DiegoBielsa** [comment]
Toda la razón, de todas formas estoy pensando que habría que dividir esta operación en 2, una que de id+nombre+imagen (diría que es necesario que el usuario tenga el id pues el nombre puede repetirse y puede haber conflictos) para proveer al usuario de las imágenes en sí y otra que te devuelva los id para que el servidor pueda ver si el cambio de banner, etc, es correcto y que no te la están intentando liar

**Comment by DiegoBielsa** [comment]
Conclusión: Para móvil esta operación es suficiente pues tiene las imágenes cacheadas, para web habría que hacer una que de "todo", pero como esta es la API de móvil está bien así.
