### ISSUE TITLE
Memoria Partidas

### ISSUE THREAD

**Issue by danielbenedi6** [UNIZAR-30226-2021-13/UniTrivia_backend#28]
Hay que definir la estructura de datos junto con las operaciones (TAD) en clase para almacenar en memoria RAM toda la información de la partida. Debe contener el estado de la sala: identificador (5 caracteres), si huecos libres, estado (jugando o esperando) y si se está jugando partida: los jugadores, el orden en el que les toca, el turno actual, los quesitos que tiene cada jugador y la posición de cada jugador. Se ha pensado en utilizar node-cache pero se puede utilizar otras cosas.

**Comment by Alejandro-Artal** [comment]
Completada
