### ISSUE TITLE
Crear Esquema BD para tienda

### ISSUE THREAD

**Issue by danielbenedi6** [UNIZAR-30226-2021-13/UniTrivia_backend#3]
Debe contener:

- ID. Es único y se referenciará por ahí (poner como nombre _id) (**obligatorio**)
- Nombre (**obligatorio**)
- Tipo. Es una enumeración de ["forma", "avatar", "banner"] (**obligatorio**)
- Precio (**obligatorio**)
- Imagen. Es el contenido binario (**obligatorio**)

**Comment by Alejandro-Artal** [comment]
Hecha
