### ISSUE TITLE
Definiciación de la API para iniciar sesión como usuario

### ISSUE THREAD

**Issue by danielbenedi6** [UNIZAR-30226-2021-13/UniTrivia_backend#6]
Se debe definir el entrypoint de la API para iniciar sesión como un usuario registrado junto a los parámetros que hay que pasarle para crearlo y qué devuelve en caso de correcto y en caso de error. La especificación tiene que hacerse utilizando OpenAPI.

**Comment by Alejandro-Artal** [comment]
Hecha
