### ISSUE TITLE
Definición de la API para cambiar la contraseña de un usuario

### ISSUE THREAD

**Issue by danielbenedi6** [UNIZAR-30226-2021-13/UniTrivia_backend#9]
Se debe definir el entrypoint de la API para cambiar la contraseña de un usuario registrado junto a los parámetros que hay que pasarle para crearlo y qué devuelve en caso de correcto y en caso de error. La especificación tiene que hacerse utilizando OpenAPI. Deben existir dos métodos, uno para obtener la pregunta (puede ser el get) y otro para la respueta con la nueva contraseña (puede ser el post del mismo endpoint)

**Comment by Alejandro-Artal** [comment]
Hecha
